#!/usr/bin/env bash

##############################################
#                                            #
# Lightbulbs, the genius idea capturing tool #
# https://github.com/zer0theory/lightbulbs   #
#                                            #
##############################################


# Set your Lightbulb Directory here
LIGHTBULB_DIR=~/Lightbulbs/

if [ ! -d "$LIGHTBULB_DIR" ]; then
  echo "Creating Lightbulbs Directory: $LIGHTBULB_DIR"
  mkdir "$LIGHTBULB_DIR"
fi

NEXT_LIGHTBULB_NUM=0

if [ "$(ls -A "$LIGHTBULB_DIR")" ]; then
  for file in "$LIGHTBULB_DIR"/lightbulb*.md; do
    filename="${file##*/}"
    num="${filename#lightbulb}"
    num="${num%.md}"
    if (( num > NEXT_LIGHTBULB_NUM )); then
      NEXT_LIGHTBULB_NUM=$num
    fi
  done
fi

NEXT_LIGHTBULB_NUM=$(printf "%03d" $((NEXT_LIGHTBULB_NUM + 1)))

NEW_LIGHTBULB_FILE="lightbulb${NEXT_LIGHTBULB_NUM}.md"

echo "# $(date +'%A, %B %d %Y, %I:%M %P')" > "$LIGHTBULB_DIR/$NEW_LIGHTBULB_FILE"


# Change nvim to your editor of choice below
nvim "$LIGHTBULB_DIR/$NEW_LIGHTBULB_FILE"


exit
